### ISSUE TITLE
Pre Trained Weights

### ISSUE THREAD

**Issue by ManishSahu53** [ManishSahu53/solarHotspotAnalysis#5]
Latest Weights: 
https://github.com/ManishSahu53/solarHotspotAnalysis/releases/download/1.1/yolov3_ckpt_49.pth

Invalid Link:
https://drive.google.com/file/d/1ZfrRN6YaxVwIG3i-g2K_BP3D2pWfzOF0/view?usp=sharing

**Comment by MichaelMarav** [comment]
Hello, the link above does not work. The message is: "Sorry, the file you have requested does not exist."
Could you please provide a new shared link?
Thank you.

**Comment by ManishSahu53** [comment]
@MichaelMarav Here is the weight file: https://github.com/ManishSahu53/solarHotspotAnalysis/releases/download/1.1/yolov3_ckpt_49.pth

**Comment by ManishSahu53** [comment]
<img width="1536" alt="Screenshot 2022-06-14 at 11 17 32 AM" src="https://user-images.githubusercontent.com/27155127/173502541-50919999-37a6-4acd-a42c-03f2a117d7fc.png">
